"""Stage 3 of the paper compiler: render the Paper into LaTeX.

Emits the COMAP-compliant document skeleton, extracted from the official
template bundled at ``templates/paper/comap_latex/MCM-ICM_Summary.tex``:

  - ``\\documentclass[12pt]{article}`` with the official geometry
  - ``newtxtext`` + ``newtxmath`` (the official font packages)
  - ``fancyhdr`` with ``\\rhead{Page \\thepage}``
  - the page-1 summary sheet, which is a FORM built from a 3-column tabular,
    not a section heading (76.6% of papers carry it)
  - a table of contents, universal in 2022-2025 (100% of 86 papers)

Everything that varies per build is written to ``generated/`` so the checked-in
sources stay hand-editable.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Dict, List, Optional

from ..schemas import Paper, PaperSection, SectionKind
from .resolver import (
    NOTATION_DISCLAIMER,
    ResolvedContext,
    model_macros,
    notations_rows,
)

# The official COMAP preamble, verbatim where it matters.
PREAMBLE = r"""\documentclass[12pt]{article}
% ---------------------------------------------------------------------------
% GENERATED by mcmcore.compiler - edits here are overwritten on every build.
% Source of truth: project.yaml, paper/paper.yaml, models/, results/atoms.yaml
% ---------------------------------------------------------------------------
\usepackage[left=1in,right=0.75in,top=1in,bottom=1in]{geometry}
\usepackage{newtxtext}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage{newtxmath}
\usepackage{graphicx}
\usepackage{fancyhdr}
\usepackage{booktabs}
\usepackage{array}
\usepackage{longtable}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}

\newtheorem{assumption}{Assumption}
\newcommand{\lit}[1]{#1}   % marks a number that is NOT a result

% Generated number macros (one per ResultAtom rendering)
\input{generated/numbers.tex}
% Generated model-name macros (so a rename propagates everywhere)
\input{generated/models.tex}

\pagestyle{fancy}
\lhead{}
\chead{}
\rhead{Page \thepage}
\lfoot{}
\cfoot{}
\rfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}
"""


class SectionWriter:
    """Turns a PaperSection into a LaTeX fragment."""

    def __init__(self, ctx: ResolvedContext) -> None:
        self.ctx = ctx

    def heading(self, section: PaperSection) -> str:
        cmd = {1: "section", 2: "subsection", 3: "subsubsection"}.get(section.level, "section")
        return f"\\{cmd}{{{section.title}}}\\label{{sec:{section.id}}}"

    def body(self, section: PaperSection) -> str:
        """Render a section body, substituting nothing and reordering nothing.

        The body is authored prose in LaTeX with atom references already in
        place (``\\numRSquared{}``). The compiler's job is to make unresolved
        references loud, not to rewrite the prose.

        The one rewrite it does perform is unwrapping ``\\lit{...}``.
        That macro is the auditor's escape hatch for numbers that are not
        results (dates, page counts, thresholds). It is not a LaTeX command,
        so leaving it in produces ``Undefined control sequence`` and no PDF.
        Unwrapping keeps the marker in the source -- where the auditor reads
        it -- and removes it from the output, which is what the author meant.
        """
        return normalise(section.body)

    def generated_body(self, section: PaperSection) -> str:
        """Build the body for sections whose content comes from records."""
        if section.kind == SectionKind.NOTATIONS:
            return self._notations()
        if section.kind == SectionKind.REFERENCES:
            return r"\bibliographystyle{plain}" + "\n" + r"\bibliography{generated/references}"
        if section.kind == SectionKind.REPORT_ON_AI:
            return self._ai_report()
        return ""

    # -- generated blocks --------------------------------------------------

    def _notations(self) -> str:
        rows = notations_rows(self.ctx.math)
        if not rows:
            return "% (no symbols recorded)"
        lines = [
            r"\begin{longtable}{lll}",
            r"\toprule",
            r"Symbol & Definition & Unit \\",
            r"\midrule",
            r"\endhead",
        ]
        for glyph, meaning, unit in rows:
            lines.append(f"{glyph} & {_escape(meaning)} & {_escape(unit)} \\\\")
        lines.extend([
            r"\bottomrule",
            r"\end{longtable}",
            "",
            # The corpus standard, near-verbatim across five papers.
            r"\noindent\textit{Note: " + NOTATION_DISCLAIMER + "}",
        ])
        return "\n".join(lines)

    def _ai_report(self) -> str:
        """The COMAP-mandated disclosure section.

        Page-limit EXEMPT, and required whenever AI was used. Rendered even when
        the record is empty, so the omission is visible rather than silent.
        """
        usage = self.ctx.ai_usage
        lines = [
            "This section is required by COMAP whenever AI tools were used, and",
            "is exempt from the page limit.",
            "",
        ]
        entries = usage.entries
        if not entries:
            lines.append("No AI tools were used in the preparation of this report.")
            return "\n".join(lines)

        lines.append(r"\begin{longtable}{p{0.22\linewidth}p{0.14\linewidth}p{0.56\linewidth}}")
        lines.append(r"\toprule")
        lines.append(r"Tool & Phase & Purpose \\")
        lines.append(r"\midrule")
        lines.append(r"\endhead")
        for e in entries:
            in_report = "yes" if getattr(e, "in_report", False) else "no"
            lines.append(
                f"{_escape(e.tool)} & {_escape(e.phase)} & "
                f"{_escape(e.purpose)} (in report: {in_report}) \\\\"
            )
        lines.extend([r"\bottomrule", r"\end{longtable}"])
        return "\n".join(lines)


def _escape(text: str) -> str:
    """Escape LaTeX specials in a plain-text field (not in authored prose)."""
    out = text
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                 ("$", r"\$"), ("#", r"\#"), ("_", r"\_"),
                 ("{", r"\{"), ("}", r"\}")):
        out = out.replace(a, b)
    # The backslash replacement above would mangle the escapes we just wrote,
    # so undo the double-escaping it introduced.
    out = out.replace(r"\textbackslash{}textbackslash{}", r"\textbackslash{}")
    return out


PLACEHOLDER = re.compile(r"\{\{([a-zA-Z0-9_]+)\}\}")


def neutralise_placeholders(text: str) -> str:
    """把还没填的 ``{{占位符}}`` 变成能编译的可见标记。

    为什么必须处理：``{{`` 在 LaTeX 里是嵌套分组，落进正文会让 TeX
    报 "I've inserted a begin-math/end-math symbol" 这类**完全指不到
    病灶**的错。刚 scaffold 出来的论文一编译就失败，用户会以为工具坏了。

    处理成 ``[TODO: name]``，理由有两条，都是编译失败换来的：

    1. **必须纯 ASCII**。中文标记看着亲切，但它会进 pdflatex，
       而 pdflatex 遇到中文直接崩（Unicode character not set up）。
       那就从一个编译失败换成另一个编译失败，白改。
    2. **下划线要转义**。占位符名里几乎都有 ``_``（prior_work_and_gap），
       而 ``_`` 在 LaTeX 里是数学专用字符，裸写会报
       "Missing $ inserted" —— 报错指向的位置和真实原因差得很远。

    3. **保留一层花括号**。占位符常常**就是**花括号本身：
       ``\includegraphics{{figure_file}}`` 里 ``{{figure_file}}``
       就是那个参数。如果替换成不带括号的文本，``\includegraphics``
       的参数就没了，报 "File not found" 之类的错。所以标记写成
       ``{TODO-name}``，括号结构原样保留。

    正文照样编译、占位符在 PDF 里一眼可见，而且不假装内容已经写好。
    审计仍会照常报"有未填占位符"。
    """
    def _mark(m):
        name = m.group(1).replace("_", r"\_")
        return "{TODO-" + name + "}"

    return PLACEHOLDER.sub(_mark, text or "")


def unwrap_literals(text: str) -> str:
    """把 ``\\lit{...}`` 展开成它的内容。

    这个宏是审计器的逃生口：标记"这个数字不是结果"（年份、页数、
    阈值）。它不是 LaTeX 命令，留在正文里会导致
    ``Undefined control sequence`` 并且**编译不出 PDF**。
    展开后标记仍留在源文件里供审计读，只是不进最终排版。
    """
    import re

    # 两种写法都要认：\lit{..} 和 \\lit{..}。
    # 后者是历史遗留 —— 早先某次批量替换把反斜杠转义重了，
    # 结果 \lit 被当成"未定义命令 \ + 文字 lit"，编译报错信息
    # 还指向别处，很难查。这里一次性兼容掉。
    out = re.sub(r"\\\\lit\{([^}]*)\}", r"\1", text or "")
    out = re.sub(r"\\lit\{([^}]*)\}", r"\1", out)
    return out



def repair_split_macros(text: str) -> str:
    r"""修被换行劈开的宏引用。

    病灶：早先某次批量编辑把 ``\numBeta{}`` 的反斜杠吃掉了，
    剩下的 ``n`` 又和后面的字面 ``\n`` 拼在一起，于是存档里出现
    ``"... is $\beta = \n\numBeta{}$"`` 这种形状。渲染时 LaTeX 报的
    是一句完全不指向病灶的 ``Undefined control sequence``，
    而 PDF 直接产不出来 —— 我在样例论文上就是这么卡了三轮。

    共同特征：反斜杠后面接换行，再接半截宏名（``umBeta``）。
    把它们接回 ``\numBeta``。放在渲染入口而不是只改数据，
    是因为存档可能已经被写坏，用户不该为了改一句话去编 YAML。
    """
    import re

    if not text:
        return text or ""
    # 反斜杠 + 换行 + umXxx{   ->   \numXxx{
    out = re.sub("\\\\\\n\\s*um(?=[A-Z])([A-Za-z]*)\\{", "\\\\num\\1{", text)
    # 已经变成 \umXxx{ 的（宏名开头的 n 被吃掉）
    out = re.sub("\\\\um(?=[A-Z])([A-Za-z]*)\\{", "\\\\num\\1{", out)
    # 收换行时反斜杠被一起吞掉的裸 umXxx{：前面既不是反斜杠也不是字母
    out = re.sub("(?<![\\\\A-Za-z])um(?=[A-Z])([A-Za-z]*)\\{",
                 "\\\\num\\1{", out)
    return out


def tide_inline_math(text: str) -> str:
    r"""把行内数学 ``$...$`` 内部的换行收成空格。

    LaTeX 的行内数学不能跨空行。把字面 ``\n`` 转成真换行时若落在
    ``$`` 中间，TeX 会报 ``I've inserted a begin-math/end-math symbol``
    —— 同样不指向真正的原因。
    """
    if not text or "$" not in text:
        return text or ""
    out = []
    in_math = False
    for i, ch in enumerate(text):
        if ch == "$" and (i == 0 or text[i - 1] != "\\"):
            in_math = not in_math
            out.append(ch)
        elif in_math and ch == "\n":
            if out and out[-1] != " ":
                out.append(" ")
        else:
            out.append(ch)
    return "".join(out)


def normalise(text: str) -> str:
    """正文进 LaTeX 前的统一整理。

    顺序有讲究，而且是踩出来的：**先收数学里的换行，再修宏**。

    反过来做会出事 —— 先修宏把 ``\n\numBetaFit`` 接成 ``\numBetaFit``，
    接着收换行时那个反斜杠前面正好是换行，被一起吞成空格，
    宏又坏了。先收换行则变成 `` umBetaFit``，而"缺反斜杠的 umXxx"
    正是 repair_split_macros 认得的形状。
    """
    out = tide_inline_math(text or "")
    out = repair_split_macros(out)
    return neutralise_placeholders(unwrap_literals(out.strip()))


def summary_sheet(paper: Paper) -> str:
    """Render page 1: the COMAP summary sheet FORM.

    Structure follows the official template: a 3-column tabular holding the
    "Problem Chosen" box, the "MCM/ICM Summary Sheet" title, and the "Team
    Control Number" box, followed by the summary prose and keywords.
    """
    s = paper.summary
    letter = (s.problem_letter or "").strip() or "X"
    team = (s.team_control_number or "").strip() or "0000000"
    keywords = ", ".join(s.key_words) if s.key_words else ""
    body = normalise(
        s.body or ""
    ) or "% (summary text not yet written)"

    header = r"""\begin{center}
\large\textbf{Problem Chosen}\hfill\textbf{Summary Sheet}\hfill\textbf{Team Control Number}\\
\rule{\textwidth}{0.4pt}
\end{center}
\begin{center}
\Large\textbf{%s}\hfill\textbf{%s}\hfill\textbf{%s}
\end{center}
\vspace{0.5em}
""" % (letter, _problem_title(letter), team)

    tail = ""
    if keywords:
        tail = f"\n\n\\vspace{{1em}}\n\\noindent\\textbf{{Keywords:}} {_escape(keywords)}\n"

    return header + "\n" + body + tail


def _cites(body: str, label: str) -> bool:
    """True when a section body references the given label."""
    if not body or not label:
        return False
    import re

    for m in re.finditer(r"\\(?:ref|eqref|autoref)\{([^}]*)\}", body):
        if label in [k.strip() for k in m.group(1).split(",")]:
            return True
    return False


def _problem_title(letter: str) -> str:
    return "MCM/ICM Summary Sheet"


def render_main_tex(paper: Paper, ctx: ResolvedContext) -> str:
    """Render the complete main.tex for a Paper."""
    writer = SectionWriter(ctx)
    parts: List[str] = [PREAMBLE]

    # -- summary sheet (page 1, not a section) -----------------------------
    parts.append(r"\begin{document}")
    parts.append(r"\thispagestyle{empty}")
    parts.append(summary_sheet(paper))
    parts.append(r"\newpage")

    # -- table of contents -------------------------------------------------
    if paper.latex.toc:
        parts.append(r"\tableofcontents")
        parts.append(r"\newpage")

    # -- sections ----------------------------------------------------------
    placed_figures: set = set()
    placed_tables: set = set()

    for section in ctx.sections:
        if not section.enabled:
            parts.append(f"% [disabled] {section.title}")
            continue
        parts.append(writer.heading(section))
        body = (
            writer.generated_body(section)
            if section.generated
            else writer.body(section)
        )
        parts.append(body)

        # Place artifacts that BELONG to this section. An artifact is placed in
        # the section that cites it; anything never cited is still placed, at
        # the end of the last authored section, so a bound figure can never be
        # silently dropped from the document.
        for figure in ctx.figures:
            if figure.id in placed_figures:
                continue
            if _cites(body, figure.label):
                from .artifacts import figure_include

                parts.append(figure_include(figure, build_ok=figure.available))
                placed_figures.add(figure.id)

        for table in ctx.tables:
            if table.id in placed_tables:
                continue
            if _cites(body, table.label):
                parts.append(rf"\input{{tables/{table.id}.tex}}")
                placed_tables.add(table.id)

        parts.append("")

    # -- orphans: bound but never cited ------------------------------------
    orphan_figs = [f for f in ctx.figures if f.id not in placed_figures]
    orphan_tabs = [t for t in ctx.tables if t.id not in placed_tables]
    if orphan_figs or orphan_tabs:
        parts.append(r"\section*{Figures and Tables}")
        parts.append(
            "% These artifacts are bound to result atoms but are not cited in "
            "the text. Only 37% of figures in published papers are cited, so "
            "the auditor reports this as a warning rather than an error."
        )
        from .artifacts import figure_include

        for figure in orphan_figs:
            parts.append(figure_include(figure, build_ok=figure.available))
            placed_figures.add(figure.id)
        for table in orphan_tabs:
            parts.append(rf"\input{{tables/{table.id}.tex}}")
            placed_tables.add(table.id)
        parts.append("")

    parts.append(r"\end{document}")
    return "\n".join(parts)


def render_models_tex(sections) -> str:
    """Emit the model-name macros file."""
    macros = model_macros(sections)
    lines = [
        "% GENERATED - model names, so a rename propagates to every mention.",
        "",
    ]
    for name in sorted(macros):
        lines.append(f"\\newcommand{{\\{name}}}{{{_escape(macros[name])}}}")
    lines.append("")
    return "\n".join(lines)


def render_references_bib(references) -> str:
    """Emit a BibTeX file from Reference records.

    COMAP requires AI tools to appear in the References, so ``ai_generated``
    entries are emitted with an explicit note rather than silently included.
    """
    lines: List[str] = ["% GENERATED from paper/references.yaml", ""]
    for r in references:
        lines.append(f"@{(r.type or 'article')}{{{r.key},")
        if r.title:
            lines.append(f"  title = {{{r.title}}},")
        if r.authors:
            lines.append(f"  author = {{{' and '.join(r.authors)}}},")
        if r.year:
            lines.append(f"  year = {{{r.year}}},")
        if r.venue:
            lines.append(f"  journal = {{{r.venue}}},")
        if r.url:
            lines.append(f"  url = {{{r.url}}},")
        if r.ai_generated:
            lines.append("  note = {AI tool, disclosed per COMAP policy},")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)
