/**
 * 界面文案集中定义。
 *
 * 所有给用户看的文字都从这里取，不要在渲染代码里硬编码字符串。
 * 两个原因：
 *   1. 同一个概念在九个屏幕里出现十几次，散落各处必然出现不一致的叫法；
 *   2. 术语以面板用词为准，文案集中才审得动。
 *
 * 注意：RES-0142、FIG_STALE、build 这类**标识符是数据不是文案**，不能翻译，
 * 翻译了用户就没法把界面和 project.yaml / 报错 / 文档对应起来。
 */

export const T = {
  // ---- 通用 ----
  loading: '正在加载…',
  loadFailed: '这个页面加载失败',
  retry: '重试',
  none: '无',
  none_yet: '暂无',
  close: '关闭',
  confirmDelete: '确定要删除吗？删掉之后要重新加回来。',
  cancel: '取消',
  confirm: '确定',
  apiDown: '连不上 MCMtools 服务',
  apiDownHint: '请在项目目录下运行：',

  // ---- 侧栏 ----
  brandSub: 'tools',
  workflow: '建模流程',
  buildGroup: '构建',
  setupGroup: '设置',

  // 屏幕名（导航）
  nav: {
    overview: '总览',
    data: '数据',
    math: '数学内容',
    params: '参数',
    experiments: '实验',
    runs: '运行记录',
    figures: '生图工作台',
    diy: '自定图表',
    references: '参考文献',
    results: '结果',
    paper: '论文',
    audit: '审计',
    problems: '选题',
    settings: '设置',
  },

  // 阶段名（与 project.yaml 的 phase 字段对应，保留英文标识）
  phase: {
    problem_selection: '选题中',
    problem_locked: '已锁定题目',
    build: '建模构建',
    finalize: '定稿提交',
  },

  // 步骤状态
  step: { done: '已完成', partial: '进行中', todo: '未开始' },

  // 模式
  mode: {
    development: '开发模式',
    competition: '竞赛模式',
    devHint: '开发模式：可以使用 AI 辅助。',
    compHint: '竞赛模式：禁止联网，拒绝 AI 辅助命令。',
  },

  // ---- 总览 ----
  overview: {
    title: '总览',
    noProblem: '还没有锁定题目',
    team: '队伍号',
    workflowCard: '建模进度',
    blockersCard: '待处理问题',
    blockerCount: (e, w) => `${e} 个错误 · ${w} 个警告`,
    noBlockers: '当前没有待处理问题。',
    statSymbols: '符号',
    statParams: '参数',
    statExperiments: '实验',
    statAtoms: '结果数字',
    statArtifacts: '图表',
    unitSymbols: '个符号',
    unitParams: '个参数',
    unitExps: '个',
    unitAtoms: '个',
    unitArtifacts: '张图 · 个表',
    staleBadge: (n) => `${n} 个已过期`,
    failedBadge: (n) => `${n} 个失败`,
  },

  // ---- 数据 ----
  data: {
    title: '数据',
    sub: '数据集、处理步骤与血缘',
    empty: '这个项目还没有数据集。',
    emptyHint: '在下面登记一份 CSV/TSV，工具会读出列名、类型和缺失值，不用手抄。',
    card: '数据集',
    colId: '编号', colName: '名称', colStage: '阶段',
    colRows: '行数', colCols: '列数', colSource: '来源',
    importTitle: '登记数据文件',
    importHint: '填文件的完整路径。导入时会校验编码、统计列类型和缺失值 —— 这些数字后面审计要用。',
    importBtn: '导入',
    fPath: '文件路径', fPathHint: '支持 CSV / TSV，需为 UTF-8 编码。',
    fName: '名称（可选）', fNamePh: '留空则用文件名',
    fKind: '来源', fKindHint: '按实际情况选：比赛方给的、网上找的、自己算出来的、模拟生成的。论文里要分别说明，来源填错会让可信度说不清。',
    kComp: '比赛方提供', kExt: '外部数据', kDer: '衍生数据', kSim: '模拟数据',
    stRaw: '原始', stStaged: '暂存', stCleaned: '已清洗',
    stProcessed: '已处理', stFeatures: '特征',
    needPath: '请填文件路径。',
    imported: (rows, cols) => `已导入：${rows} 行、${cols} 列。`,
    importFailed: '导入失败：',
    delFailed: '删除失败：',
    fromDisk: '从磁盘导入',
    fromDiskHint: '直接填磁盘上的路径，不用先把内容复制进来。相对路径按项目目录解析 —— 把 CSV 丢进 data/ 之后写 data/xxx.csv 就行。',
    pathPh: 'data/wordle.csv 或 /完整/路径/data.csv',
  },

  // ---- 代码骨架（实验页）----
  snippets: {
    title: '代码骨架',
    sub: '选一个骨架直接生成能跑的实验脚本，不用从零写 run.py。',
    use: '用这个骨架建实验',
    viewSource: '看骨架源码',
    inputs: '骨架需要的输入',
    deps: '依赖',
    created: (id) => `已建好 ${id}，run.py 也写好了，可以直接运行。`,
    createFailed: '建实验失败：',
    empty: '没有找到代码骨架。',
    nameLabel: '实验名字（可留空）',
    namePh: '留空则用骨架的名字',
    variedLabel: '变动参数（可留空）',
    variedHint: '一行一个，写成 参数名=值,值,值。例如 w=0.1,0.5,1.0 —— 填了它实验就会跑多次，每次一个取值。',
    create: '建实验',
    pick: '选骨架',
  },

  // ---- 脚本编辑器（实验页）----
  script: {
    title: '实验脚本 run.py',
    sub: '在这里改模型、直接运行。返回值必须包在 {"atoms": [...]} 里。',
    save: '保存',
    run: '保存并运行',
    saved: (rel) => `${rel} 已保存。`,
    saveFailed: '保存失败：',
    loadFailed: '读不到脚本：',
    noEntry: '这个实验还没有脚本。下面写点内容保存，entrypoint 会自动填好。',
    runStarted: '已开始运行，跑完看「运行记录」和「结果」页。',
    runFailed: '运行失败：',
    load: '载入',
    hint: '编辑完记得保存。语法错误会在保存时被拦下来并指出行号 —— 不会让一个坏文件先落盘、等运行时才报错。',
    lines: (n) => `${n} 行`,
    file: '文件',
  },

  // ---- 安装与路径 ----
  paths: {
    title: '安装与路径',
    sub: '程序装在哪、模板库在哪、用的哪个 Python。',
    repoRoot: '程序目录',
    appBundle: 'App 包',
    templatesRoot: '模板库',
    webRoot: '面板文件',
    projectRoot: '项目目录',
    dataDir: '数据目录',
    userDir: '自定模板目录',
    python: 'Python',
    status: '状态',
    ok: '正常',
    missing: '不存在',
    okHint: '路径正常，模板库能读到。',
    missingWarn: '这个路径不存在 —— 模板或面板可能加载不到。',
    count: (n) => `${n} 个模板`,
    readonlyHint: '程序目录是只读的（在 .app 包里时属正常）。自定图会存到「自定模板目录」，不受影响。',
    sourceBundled: '来自程序目录',
    sourceOverride: '来自环境变量指定的位置',
    sourceBundle: '来自 App 包内',
    copied: '已复制',
    refresh: '刷新',
    extraRoots: '自定模板库',
    fromApp: (p) => `从 App 包启动：${p}`,
    diagnose: '模板"不见了"先看这里：路径是程序实际在用的那一条，不是另算一份。',
  },

  // ---- 模型 ----
  math: {
    edit: '编辑',
    remove: '删除',
    save: '保存',
    saved: '已保存',
    addSymbol: '＋ 新增符号',
    addEquation: '＋ 新增公式',
    addAssumption: '＋ 新增假设',
    symbolHint: '含义会直接生成到论文符号表，写英文完整表述。',
    equationHint: '只写公式本身，不要写 \begin{equation} 和 \label。',
    assumeHint: '每条假设都要给理由，只写假设参数恒定是没写完。',
    emptyHint: '还没有内容。点上面的按钮加，或先跑一次实验。',
    colShort: '简称',
    roles: {
      state: '状态量', parameter: '参数', derived: '导出量', variable: '变量',
      index: '下标', constant: '常数', unknown: '未分类',
    },

    title: '数学内容',
    sub: '符号表、公式、假设 —— 一篇论文只有一套，跨全文唯一',
    empty: '还没有登记符号和公式。',
    symbols: '符号',
    equations: '公式',
    assumptions: '假设',
    numbered: '已编号',
    colGlyph: '符号',
    colRole: '角色',
    colMeaning: '含义',
    colUnit: '单位',
    colNumber: '编号',
    colLatex: '公式',
    colAssumption: '假设',
    dupTitle: '符号重复定义',
    dupHint: '同一个符号有两种含义，读者会被误导。改掉其中一个，或明确说明复用关系。',
    dupEqTitle: '公式编号重复',
    dupEqHint: '公式编号是全文统一的计数器，必须唯一。',
    notation: '符号表',
    notationHint: '符号表是符号的视图，自动生成 —— 不要手写，手写必然与正文脱节。',
    disclaimer: '非穷尽声明',
  },

  params: {
    addParam: '＋ 新增参数',
    sourceHint: '来源决定这个数可不可信。没交代来源的参数在 --strict 下会阻塞提交。',
    emptyHint: '还没有参数。模型里用到的每个常数都应该在这里登记，否则正文里的数字没有出处。',
    renameHint: '参数名是代码取值的键，改名不会自动改代码。',
    fittedBy: '由 ' + '',
    saveFailed: '保存失败：',
    sources: {
      literature: '文献', dataset: '数据', fitted: '拟合', assumed: '假设',
      derived: '推导', semi_educated_guess: '半经验估计', unknown: '未标注',
    },
    title: '参数',
    sub: '每个数值从哪来 —— literature / dataset / fitted / assumed',
    empty: '还没有登记参数。参数放在 params/parameters.yaml，可以直接编辑。',
    colName: '参数',
    colValue: '取值',
    colUnit: '单位',
    colSource: '来源',
    colRef: '依据',
    unresolved: '还没确定取值',
    unresolvedHint: '这些参数没有取值，实验跑起来会缺条件。',
    noProvenance: '没有标注来源',
    noProvenanceHint: '105/237 篇现代论文会列表说明参数来源。标上来源，评审才不会问"这个数哪来的"。',
    bySource: '来源分布',
    sourceUnknown: '未标注',
  },

  // ---- 实验 ----
  runs: {
    title: '运行记录',
    sub: '每次执行都单独归档，按运行号顺序排列',
    empty: '还没有运行记录。到「实验」页点运行，这里就会出现归档。',
    emptyDir: '归档目录 runs/ 还不存在。',
    colRun: '运行号',
    colStatus: '状态',
    colParams: '参数',
    colAtoms: '结果原子',
    colDuration: '耗时',
    colArtifacts: '产出文件',
    artifactsNone: '无产出',
    artifactsCount: (n) => `${n} 个文件`,
    script: '脚本',
    scriptHash: '代码指纹',
    condition: '条件',
    dir: '归档位置',
    totalRuns: (n) => `共 ${n} 次运行`,
    staleTitle: '结果来自旧代码',
    staleHint: '下面的实验代码在运行之后被改过。请重跑，否则论文里的图和数据对不上。',
    staleScript: (p) => `脚本 ${p} 已改动`,
    staleMissing: (p) => `脚本 ${p} 已不存在`,
    rerunHint: '到「实验」页重跑该实验',
    statusOk: '成功',
    statusFail: '失败',
  },
  experiments: {
    title: '实验',
    sub: '实验协议、执行状态与来源',
    empty: '还没有定义实验。',
    emptyHint: '定义一份实验协议，就能跑出带来源记录的结果 —— 正文引用的数字都从这里来。',
    card: '实验',
    newTitle: '新建实验协议',
    newHint: '最少填一个名称和类型就能建。运行前还需要一个 entrypoint（跑哪个脚本），可以之后再补。',
    createBtn: '创建实验',
    created: '实验已创建。',
    createFailed: '创建失败：',
    addVary: '+ 加一个变动参数',
    fTpl: '套模板（可选）', fTplHint: '九种常见实验设计，自带默认参数和输入说明。不确定怎么填就选一个。',
    fTplNone: '（不使用模板）',
    fLabel: '名称', fLabelHint: '写清这个实验在验证什么，例如「硬模式权重敏感性」。',
    fKind: '类型', fKindHint: '决定展开试验的方式和默认出图。敏感性分析选 OAT（逐个变）或网格。',
    fDataset: '数据集编号（可选）', fDatasetHint: '留空则不绑定数据集。绑了之后结果会记下数据来源。',
    fEntry: '运行脚本（可选）', fEntryHint: '格式 experiments/EXP-001/run.py:run，冒号后是函数名。不填则只能查看协议、不能运行。',
    fWhy: '动机（可选）', fWhyHint: '为什么做这个实验。写下来，正文里解释实验设计时能直接用。',
    varyTitle: '变动参数',
    varyHint: '每个参数给一组取值（逗号分隔）。留空的参数就保持不变。填了变动参数，实验才会真的跑多次。',
    vNamePh: '参数名，如 hard_mode_weight',
    vValuesPh: '取值，如 0.1, 0.5, 1.0',
    vUnitPh: '单位（可选）',
    varyNeedValues: '变动参数要给出取值，否则实验只会跑一次，出图也没有横轴。',
    kOat: '单因素敏感性（OAT）', kGrid: '网格敏感性',
    kCompare: '模型对比', kNoise: '噪声鲁棒性',
    kMonte: '蒙特卡洛', kCV: '交叉验证',
    kOptim: '优化求解', kConverge: '收敛性研究',
    kSim: '仿真', kTrainTest: '训练/测试划分',
    kScenario: '情景分析', kBacktest: '回测',
    kError: '误差分析', kOther: '其他',
    kind: '类型',
    runs: '运行次数',
    model: '所属模型',
    varied: '变动参数',
    heldFixed: '固定不变',
    run: '运行',
    running: '正在运行…',
    trials: '展开试验',
    trialsTitle: (id, n) => `${id} — 共 ${n} 次试验`,
    trialsHint: '实验协议展开后，实际会执行这些参数组合。',
    failedRuns: (n) => `有 ${n} 次运行失败 —— 已保留作为「被否方案」的证据。`,
    runDone: (id, n, changed, stale) => stale
      ? `${id}：${n} 次运行完成，${changed} 个数字发生变化 —— ${stale} 个图表已过期`
      : `${id}：${n} 次运行完成，数值没有变化`,
    runFailed: (msg) => `运行失败：${msg}`,
  },

  // ---- 结果 ----
  refs: {
    title: '参考文献',
    sub: '粘贴 BibTeX 导入，自动核对正文引用。',
    importTitle: '粘贴 BibTeX',
    importHint: '从期刊页面或 Google Scholar 复制 BibTeX 贴进来即可，一次可以贴多条。',
    pastePh: '@article{key,\n  title = {...},\n  author = {姓, 名 and 姓, 名},\n  journal = {...},\n  year = {2023}\n}',
    importBtn: '→ 导入',
    fillSample: '填入示例',
    exportBtn: '导出 .bib',
    listTitle: '文献列表',
    empty: '还没有文献。',
    emptyHint: '上面粘贴 BibTeX 就能导入；也可以点「填入示例」看看格式。',
    rulesTitle: '写作规则',
    colKey: '引用键', colTitle: '标题', colAuthors: '作者',
    colYear: '年份', colVenue: '期刊/会议',
    aiTag: 'AI 工具',
    missingEntry: '正文引用了不存在的文献',
    missingEntryHint: '这些 \\cite 找不到对应条目，编译出来会是 [?]。补上条目，或删掉正文里的引用。',
    uncited: '有条目但正文没引用',
    uncitedHint: '语料里 707/707 条文献都被正文引用过。没被引用的条目要么去正文引一下，要么删掉。',
    entryProblems: '条目本身有问题',
    nothingPasted: '还没有粘贴内容。',
    sampleFilled: '已填入示例，可以直接点导入试试。',
    imported: (a, r) => `已导入 ${a} 条${r ? `，覆盖 ${r} 条` : ''}。`,
    warnPrefix: '注意：',
    importFailed: '导入失败：',
    saveFailed: '保存失败：',
  },
  diy: {
    title: '自定图表',
    sub: '不写代码，点选拼出一张自定义图。画好了可以存成模板反复用。',
    loadFailed: '读不到 DIY 选项，请确认服务在运行。',
    noFont: '这台机器上没找到中文字体，图里的中文可能显示成方块。标题和轴标签建议用英文。',
    appearance: '外观',
    chartType: '图形类型',
    palette: '配色',
    titleLabel: '图标题',
    titlePh: '例如：峰值人数随传播率的变化',
    xlabel: '横轴名称',
    ylabel: '纵轴名称',
    width: '宽（英寸）',
    height: '高（英寸）',
    grid: '显示网格',
    legend: '显示图例',
    showValues: '柱状图标注数值',
    dataSection: '数据',
    multiMode: '多序列模式',
    multiHint: '需要对比多条曲线或多个方案时勾上。',
    yLabel: '数据（逗号或空格分隔）',
    yHint: '直接粘一串数字即可，例如 10, 32, 58, 74。',
    xLabel: '横轴数值（留空则用 1,2,3…）',
    xHint: '个数必须和数据一样多。',
    seriesLabel: '多序列（JSON）',
    seriesHint: '每组一个 name 和一组 y。写错了下面会直接告诉你哪里不对。',
    labelsLabel: '各项名称',
    labelsHint: '分类图用：每个柱子/扇区一个名字，个数要和数据一样多。',
    errorsLabel: '误差值',
    errorsHint: '误差棒图和误差带图用：每个点的不确定度。',
    matrixLabel: '矩阵（热力图/等高线/曲面用）',
    matrixHint: '二维数组，例如 [[1,2,3],[4,5,6]]。',
    hlines: '水平参考线',
    vlines: '垂直参考线',
    captionLabel: '图题（会印在图下方）',
    captionPh: '例如：图 1  不同传播率下的峰值人数',
    draw: '→ 画出来',
    saveAsTemplate: '存成模板',
    preview: '预览',
    drawFirst: '点「画出来」看效果。可以先随便填几个数试试。',
    askName: '给这张图起个名字（英文或数字，用来做模板 ID）：',
    savedAs: (id) => `已保存为 ${id}，可以在上面的模板列表里找到。`,
    badMatrix: '矩阵填得不对，要是二维数组，例如 [[1,2,3],[4,5,6]]。',
    badSeries: '多序列填得不对，要是数组，每项有 name 和 y，例如 [{"name":"A","y":[1,2]}]。',
    drawFailed: '画图失败：',
    saveFailed: '保存失败：',
    styleSection: '微调（每个序列各自设置）',
    styleHint: '按序列顺序列出，留空则沿用上面的配色和自动轮换的线型。多序列图里两条线只有颜色不同的话，打印成黑白就分不出来了 —— 所以默认线型是轮换的。',
    series: (i) => `序列 ${i}`,
    axisSection: '轴与刻度',
    tickSize: '刻度字号',
    legendPos: '图例位置',
    legendSize: '图例字号',
    titleSize: '标题字号',
    labelSize: '轴标签字号',
    resetStyle: '清空微调',
    advanced: '高级',
  },
  figures: {
    title: '生图工作台',
    sub: '选模板 → 填数据 → 看效果 → 导出。先看效果再决定要不要用',
    pickTemplate: '选模板',
    filterLabel: '搜索模板',
    filterHint: '输入关键词，例如：时间、分布、热力、敏感性',
    filterHits: '匹配 {n} 个模板（关键词：{q}）',
    pickData: '填数据',
    preview: '预览',
    export: '导出 PDF',
    exportDrawio: '导出可编辑文件',
    purpose: '用途',
    evidence: '语料依据',
    inputs: '需要的输入',
    required: '必填',
    optional: '可选',
    captionHint: '图注（会印在图上）',
    keysHint: '各键怎么写（等号右边是可直接用的示例值）：',
    dataHint: '按模板需要的输入名填 JSON。数组成对填，长度必须一致。',
    noCode: '这个模板只有说明、还没有绘制代码。',
    renderFail: '画不出来',
    rendering: '正在生成…',
    previewTitle: '预览',
    sample: '填入示例数据',
    backendDrawio: '可编辑图（drawio）',
    backendPlot: '数据图（matplotlib）',
    count: '个模板',
    onlyWithCode: '只看能画的',
    style: '外观微调',
    styleHint: '模板画完之后的统一调整 —— 不用改模板、也不用导出到别处再修。留空表示不改。',
    styleRemember: '记住这些设置',
    styleRememberHint: '勾上之后，换模板、下次打开都会沿用。存在浏览器本地。',
    styleReset: '全部还原',
    styleActive: (n) => `已启用 ${n} 项调整`,
  },

  results: {
    title: '结果',
    sub: '绑定到 ResultAtom 的图与表',
    figures: '图',
    tables: '表',
    empty: '暂无',
    notGenerated: '尚未生成',
    template: '模板',
    boundAtoms: '绑定数字',
    citedIn: '被引用章节',
    citedNowhere: '未被引用',
    regenerate: '重新生成',
    regenerateAll: (n) => `重新生成 ${n} 个过期项`,
    regenOk: (id) => `${id} 已按当前结果重新生成`,
    regenSkip: (id) => `${id} 未过期，无需重新生成`,
    regenFailed: (msg) => `重新生成失败：${msg}`,
    showLatex: '查看 LaTeX',
    latexNote: '尚未构建；请先在「论文」页生成 PDF。',
  },

  // ---- 论文 ----
  papers: {
    title: '论文',
    sub: '章节、生成与实时页数预算',
    build: '生成 PDF',
    building: '正在生成…',
    buildOk: (n) => `已生成 ${n} 页 PDF`,
    buildFailed: '生成失败 —— 请看「审计」页',
    buildError: (msg) => `生成失败：${msg}`,
    budget: '页数预算',
    pages: '页',
    remaining: (n) => `还剩 ${n} 页`,
    over: (n) => `超出 ${n} 页`,
    budgetHint: '2022–2025 年的获奖论文中，72% 正好是 25 页。',
    aiCard: 'COMAP 的 AI 使用合规',
    aiUsed: '是否使用 AI',
    aiEntries: '记录条数',
    aiSection: '披露章节',
    aiYes: '是',
    aiNo: '否',
    aiEnabled: '已启用',
    aiDisabled: '已停用',
    aiMissing: '缺失',
    aiNotInReport: '（未写入报告）',
    sections: '章节',
    sectionsEnabled: (n) => `已启用 ${n} 个`,
    sectionsHint:
      '顺序由模板骨架决定，是否包含由作者决定。「文献综述」永不提供 —— 415 篇论文里 0 篇有这个标题。',
  },

  // ---- 审计 ----
  audit: {
    title: '审计',
    sub: '审计发现与提交门禁',
    rerun: '重新审计',
    rerunDone: '审计已重新运行',
    ready: '可以提交',
    notReady: '请勿提交',
    readyHint: '没有错误，也没有阻塞性警告。',
    notReadyHint: (e, w) => `${e} 个错误，${w} 个阻塞性警告。`,
    errors: '错误',
    blocking: '阻塞性警告',
    blockingHint: '开启 --strict 时这些会拦截提交',
    strictCodes: '会拦截提交的检查项',
    strictHint:
      '只有工具能**证明**站不住的结论，或涉及 COMAP 合规的问题才会拦截提交。审美偏好不拦截。',
    noneFound: '无',
  },

  // ---- 选题 ----
  problems: {
    title: '选题',
    sub: '登记候选题目，然后锁定要做的那一道',
    card: '题目选择',
    hint: '锁定题目之后，侧栏会收窄到构建流程。锁定是有意为之的动作，只有明确解锁才能撤回。',
    locked: '已锁定题目',
    noneLocked: '未锁定',
    lockedHint: '题目已锁定。要换题请到「设置」解锁，或直接改 project.yaml 的 locked_problem_id。',
    listTitle: '候选题目',
    colLetter: '题号', colTitle: '标题', colNote: '读题笔记', colStatus: '状态',
    empty: '还没有登记任何题目。',
    addTitle: '登记一道题目',
    addHint: '先把 A–F 六道都登记进来，边读边排除，最后锁定一道。至少填题号或标题。',
    addBtn: '+ 登记',
    added: '已登记。',
    addFailed: '登记失败：',
    delFailed: '删除失败：',
    saveFailed: '保存失败：',
    needOne: '题号和标题至少填一个，否则之后认不出是哪道题。',
    letterHint: 'A–F。用它生成题目 ID（如 PROB-C）。',
    noteHint: '记下关键要求、数据情况、初步想法。选完题也用得上。',
    lockBtn: '锁定',
    lockTitle: '锁定题目',
    lockHint: '锁定后侧栏收窄到构建流程，这一步不可随手撤回。确认要做这道题再锁。',
    locked2: '题目已锁定。',
    lockFailed: '锁定失败：',
    teamNumber: '队伍控制号（可选）',
    teamHint: 'COMAP 的队伍控制号，会印在摘要页上。之后也能在「设置」里补。',
    lockedTag: '已锁定',
    stCandidate: '候选', stAnalysed: '已分析',
    stChosen: '已选定', stRejected: '已排除',
  },

  // ---- 设置 ----
  settings: {
    title: '设置',
    sub: '项目、队伍与运行模式',
    project: '项目',
    projectId: '项目 ID',
    phase: '当前阶段',
    lockedProblem: '已锁定题目',
    teamNumber: '队伍号',
    runMode: '运行模式',
    mode: '模式',
    netGuard: '网络拦截',
    installed: '已启用',
    notInstalled: '未启用',
    blockedOutbound: '已拦截的外连',
    modeHint: '竞赛模式会拦截网络访问、拒绝 AI 辅助命令。是真正的强制，不只是记录意图。',
    editTeam: '改队伍号',
    teamHint: 'COMAP 的队伍控制号，会印在摘要页上。比赛期间可以随时改。',
    saveFailed: '保存失败：',
    unlock: '解锁题目',
    unlocked: '已解锁，回到选题阶段。',
    unlockFailed: '解锁失败：',
  },

  // ---- 检查项（审计 code）中文说明 ----
  // key 是代码里的 code，必须原样保留；value 是给用户看的说明。
  finding: {
    FIG_STALE: '图已过期：绑定的数字变了，图还没重画',
    TAB_STALE: '表已过期：绑定的数字变了，表还没重画',
    ARTIFACT_NOT_CITED: '图表没有被正文引用',
    ARTIFACT_FILE_MISSING: '图表文件不存在，PDF 里会是一个占位框',
    ARTIFACT_UNBOUND: '图表没有绑定任何结果数字',
    ARTIFACT_NO_FILE: '图表尚未生成',
    DANGLING_ARTIFACT_BINDING: '图表绑定了不存在的结果数字',
    NUMERIC_UNBOUND: '正文里出现了没有来源的数字',
    AI_USE_UNDISCLOSED: '用了 AI，但没有「Report on Use of AI」章节',
    AI_DISCLOSURE_WITHOUT_USE: '声明了 AI 章节，但没有记录任何 AI 使用',
    SUMMARY_PLACEHOLDER: '摘要页还是模板占位内容',
    PAGE_OVERRUN: '页数超出上限',
    PAGE_BUDGET_UNDERUSED: '页数预算大量闲置',
    SENSITIVITY_WITHOUT_INVARIANT: '敏感性分析没有声明固定了哪些参数',
    OAT_NO_INVARIANT: '单因子分析没有声明不变量',
    DUPLICATE_EQUATION_NUMBER: '公式编号重复',
    DANGLING_REFERENCE: '引用了不存在的标签',
    SYMBOL_REDEFINED: '同一个符号在两个模型里含义不同',
    PARAMETER_NO_PROVENANCE: '参数没有标注来源',
    NO_VALIDATION: '没有做模型验证',
    LITERATURE_REVIEW_HEADING: '「文献综述」标题：415 篇论文里 0 篇这么写',
    MISSING_INTRODUCTION: '缺少引言',
    MISSING_REFERENCES: '缺少参考文献',
    EXP_FAILED: '实验运行失败',
    UNKNOWN_TEMPLATE: '引用了不存在的模板',
    TEMPLATE_INVALID: '模板文件本身有问题',
  },
};

/** 把审计 code 翻成中文说明；没有收录的原样返回 code。 */
export function findingLabel(code) {
  return T.finding[code] || code;
}

/** 阶段名；未知阶段原样显示，方便发现新阶段没配文案。 */
export function phaseLabel(phase) {
  return T.phase[phase] || phase;
}

/** 严重程度。 */
export function severityLabel(sev) {
  return sev === 'error' ? '错误' : sev === 'warning' ? '警告' : '提示';
}
